version: 2
updates:
  -  package-ecosystem: "gradle"
     directory: "/"
     schedule:
       interval:"daily"
       time: "18:30"
      # Use Japan Standard Time (UTC +09:00)
      timezone: "Asia/Tokyo"
